### ISSUE TITLE
Sammy 0.5.1 on FF3.0.x runs the route twice probably because of polling...

### ISSUE THREAD

**Issue by rmanalan** [quirkey/sammy#15]
Hi Aaron.  I just started testing an app that works great on FF3.6/Chrome/Safari4.x, but when I run it on FF3.0.x, I noticed that I started getting dup calls to my Sammy routes causing duplicate ajax requests to be run.  I'm trying to debug it, but thought I should file a bug.  Have you heard of this?  Here's the log:

[Tue Mar 09 2010 21:01:26 GMT-0800 (PST)] no native hash change, falling back to polling
[Tue Mar 09 2010 21:01:26 GMT-0800 (PST)] runRoute get #/
GET http://wc/rest/api/resourceIndex
[Tue Mar 09 2010 21:01:26 GMT-0800 (PST)] no native hash change, falling back to polling
[Tue Mar 09 2010 21:01:26 GMT-0800 (PST)] runRoute get #/

Thanks!

Rich

**Comment by quirkey** [comment]
Hey Rich

I havent actually seen any issues with 3.0.x lately. In fact I was just testing a new client app I've been working on today in 3.0.8 because we were debugging CSS issues and Sammy seem to run without issue. 

Just from a glance, those log messages seem to indicate that the page itself is getting reloaded (or at least the app is) because the 'no native hash change method' only happens once, when the app loads.

Let me know if you find anything else, I'll leave the ticket open.

**Comment by rmanalan** [comment]
Found it... I somehow was loading my app.js twice (fat fingers). Thanks for the prompt response, Aaron. I just love Sammy! The odd thing was that FF3.6 ignores the second declaration, but 3.0.x doesn't.

Anyway, thanks!!

Rich
