### ISSUE TITLE
jqm+sammy: Routing w/ params not working

### ISSUE THREAD

**Issue by shift2design** [quirkey/sammy#157]
I am new to sammy.js and knockout.js. I have Sammy routes working with the exception of parameters. I can actually get the params to log to console properly but I get a 404 error. For example, #news-detail works but #news-detail/101 will not. I posted the sample app I just started. Any help or insight is greatly appreciated:

http://shift2design.com/wip/lakeside-mobile-01/index.html#news

**Comment by endor** [comment]
I am not sure how this is supposed to work, but it seems that on a hash change which happens when you click on a news item, jquery mobile will react and remove the '#' from the hash if it is a path (includes a '/'). Then it tries to load that page and fails (404) and returns to the first page. It is easier to debug if you include the unminified versions of the files. Doesn't really seem sammy related. Btw, if the route for '' is just for the first start, you can do run('#home') as well. That's a bit nicer.
