### ISSUE TITLE
again: IE8 is not working with haml.js

### ISSUE THREAD

**Issue by andywenk** [quirkey/sammy#158]
Hi Aaron,

I am using the latest sammy.js version with the haml.js plugin. I was reading https://github.com/quirkey/sammy/pull/94 and am using the haml.js code from the plugin. But I still get an error when opening the site in IE8. You can find it here: http://gammalife.nms.de. The setup is

```
 <script type="text/javascript">
  $LAB
  .script("/javascripts/vendor/jquery.js")
  .script("/javascripts/vendor/underscore.js")
  .script("/javascripts/vendor/haml.js")
  .script("/javascripts/vendor/sammy/sammy.js")
  .script("/javascripts/vendor/sammy/plugins/sammy.json.js")
  .script("/javascripts/vendor/sammy/plugins/sammy.haml.js")
  .script("/javascripts/vendor/sammy/plugins/sammy.storage.js")
  .script("/javascripts/namespace.js")
  .script("/javascripts/helper.js")
  .script("/javascripts/application.js")
  .script("/javascripts/E1/widgets/navigation.js")
  ;
 </script>
```

where 

jquery is 1.8.1
lab is 2.0.3
underscore is 1.3.3
sammy is 0.7.1

The error in IE8:

message: Object expected
line: 71
character: 9
Code: 0
URI: http://gammalife.nms.de/javascripts/vendor/sammy/plugins/sammy.haml.js

So this is the code:

```
66     var haml = function(template, data, name) {
67       // use name for caching
68       if (typeof name == 'undefined') { name = template; }
69       var fn = haml_cache[name];
70       if (!fn) {
71         fn = haml_cache[name] = Haml(template);
72       }
73       return fn($.extend({}, this, data));
74     };
```

So the error occurs while initiating the Haml. Any idea where the problem is in IE8? IE9 works as expected. I don't want to change Haml because I am so fuckin' used to it in Rails ;-)

Thanks a lot and ... see ya hopefully at jsconf.eu next month ;-)

Cheers

Andy

**Comment by endor** [comment]
Hey Andy,

when I went through the tests in sammy to make them asynchronous I noticed that, too - there is an IE8 syntax error in sammy.haml.js. I tried to investigate it further and what I found was: the problem seems to be that we're calling Haml() instead of new Haml(). If we're calling new Haml() though there's a new syntax error in the haml.js file, which is that IE8 doesn't seem to like the 'Haml = function Haml()' syntax. And even if we remove the second Haml from that line there's another syntax error - something with trim. So either I am using Haml in a way I am not supposed to or it's just not ment to be used with IE8. I don't think this is Sammy's fault though. Or are you using Haml.js in a different environment where it's working with IE8?

Frank

**Comment by andywenk** [comment]
Hey Frank,

thanks for your feedback. I already read, that the original intention for haml.js was the usage on the server side. But as far as I understood in other messages here, someone fixed the IE8 problems and Aaron pulled it into the sammy repo.

I am also sure, that this is no sammy bug. But I thought the best place to open a request again is here, because there has already been a discussion here. 

No I am using haml.js the first time and only in sammy. I guess I should check if the error is similar if using haml.js independently wit IE8. I will let you know.

Cheers

Andy

**Comment by endor** [comment]
Can we close this?
