### ISSUE TITLE
Trying to map for Script#, could use better details

### ISSUE THREAD

**Issue by dealproc** [quirkey/sammy#159]
Does anyone have a better API document then what currently exists fro how you use Sammy?  I'm trying to build out the class structure(s) for using Script# right now, and I'm quickly realizing that there are a lot of dependencies on anonymous types. (e.g. the Application.Before(...) call, where you can pass options... it's not quite detailed what can/cannot be done there).

Any help would be appreciated.

**Comment by endor** [comment]
The best documentation are probably the tests and the code itself. If you have specific questions, they are best directed at the mailing list, since this is for bugs/improvements. The options you can pass to before are documented in contextMatchesOptions as noted at the bottom of the before documentation.
