### ISSUE TITLE
Encoded url can not be routed properly

### ISSUE THREAD

**Issue by SeanDongX** [quirkey/sammy#194]
Encoded url like /app2/#/property%23169 (/app2/#/property#169) can not be routed properly by routing rule  this.get('/app2/#/property#:Id', ...)

**Comment by endor** [comment]
I am not entirely sure that this should work. It's not the same route after all.. what if you want to have exactly this route: "property%23169"? If you're looking for a solution to your specific problem, you could use a regular expression instead of the string in the route and allow both '#' and '%23'.

**Comment by SeanDongX** [comment]
Hmm. you are right. I will close this issue then.
Thanks
