### ISSUE TITLE
this.use(Sammy.Store) throws error in 0.6.2

### ISSUE THREAD

**Issue by rmanalan** [quirkey/sammy#62]
Take a look at http://dl.dropbox.com/u/163514/sammy.storage.bug/index.html

You can reproduce this bug simply by using Sammy.Store.

```
Sammy('#main',function(){
    this.use(Sammy.Store); // offending code
    this.get('#/',function(){
      this.swap('SUCCESS!');
    });
}).run('#/');
```

**Comment by quirkey** [comment]
Hey Rich

This is actually because Sammy.Store isn't a plugin. Sammy.Store is just a prototype that theoretically could be used without Sammy. Sammy.Storage is the plugin that implements access to Sammy.Store for Sammy apps. This probably means I need to add better docs and/or a better way to define/describe plugins.

**Comment by rmanalan** [comment]
Ah I see.  I should have looked at the code closer.  Thanks.
