### ISSUE TITLE
After calling swap consider triggering "change" automatically

### ISSUE THREAD

**Issue by tomzee** [quirkey/sammy#8]
I noticed that when I load template code (using swap) that contains a form, its submit doesn't get intercepted. 

Proposed change to swap:

```
swap: function(content) {
  var s = this.$element().html(content);
  this.trigger('changed');
  return s;
},
```

The workaround, for now is that the user code will just have to call this trigger after swapping.

**Comment by quirkey** [comment]
In order to make this happen we'll have to move some code around as changed is actually fired _after_ swap. the benefit of the current approach is that if you redefine swap you dont have to worry about calling 'changed'. I guess its a bit of a tradeoff. jQuery 1.4 is dropping soon with support for capturing submit events with live() so it might make the 'changed' event obsolete.

**Comment by quirkey** [comment]
This has become obsolete with Sammy 0.5 and live event handling.
